### ISSUE TITLE
Gapless playback for ALAC

### ISSUE THREAD

**Issue by vit9696** [dimitris-c/AudioStreaming#101]
Hello, in #88 it was mentioned that sometimes the beginning of the audio is cut off for flac files and that was fixed. I do not have flac files nearby to confirm the fix but at least for alac it is not working for me.

Consider the following files from the attachment:
* [26 Le val d'amour.m4a.zip](https://github.com/user-attachments/files/18048356/26.Le.val.d.amour.m4a.zip)
* [27 La volupté.m4a.zip](https://github.com/user-attachments/files/18048357/27.La.volupte.m4a.zip)

When they are queued one after another there is a noticeable gap upon switching from 26 to 27. For testing I used a customised version of amperfy if that helps (https://github.com/vit9696/amperfy), but I do not believe there is anything special in the app itself. I confirmed that the files are gapless via Audacity.

Could you please recheck that AudioStreaming works correctly in gapless scenarios for lossless formats? Thanks!

**Comment by dimitris-c** [comment]
I tested this using the example project and I do not notice any gap between. 
I queue the files by using the `.queue(url:)` method one after the other

**Comment by dimitris-c** [comment]
Here's a QuickTime screen grab and the files, remotely loaded - also tested with local files with same result

https://github.com/user-attachments/assets/327fa8cc-0adf-4f69-8737-97cdb8089253

**Comment by vit9696** [comment]
Thank you for taking your time and testing it. I tracked down the issue: amperfy defaults are transcode to mp3 for all data. Apparently during my tests some of the files were cached as mp3 before I changed the things, and thus the wild situation with gapless. Closing the issue and sorry for extra trouble ^^
