### ISSUE TITLE
Audio Plot Request

### ISSUE THREAD

**Issue by iDevelopper** [dimitris-c/AudioStreaming#20]
Hi,

What about an audio plot graph?

Is it possible? It would be extra!

Cheers,

**Comment by dimitris-c** [comment]
This falls outside of this library scope, I believe this can be achieved using frame filters

**Comment by iDevelopper** [comment]
Ah! Can you pride an example?

**Comment by dimitris-c** [comment]
Have a look at https://github.com/AudioKit/AudioKitUI there are great resources and examples that you can adapt and use with AVAudioEngine.

**Comment by iDevelopper** [comment]
I already tried. Showing a plot with this library takes a long time! About 15-30 seconds for a 5 minute song.

**Comment by iDevelopper** [comment]
It would be interesting to all the users that your library should be completed by integrating an audio analyzer (for a visualization by bars and others) and a plot.

Cheer,

**Comment by iDevelopper** [comment]
Ok, never mind, thank you.
