### ISSUE TITLE
Frame filter buffer size

### ISSUE THREAD

**Issue by iDevelopper** [dimitris-c/AudioStreaming#22]
Hi,

May I ask you why the size of the buffer received in the call back of FilterEntry is so large (mDataByteSyze)? (17640 instead of 2048 for StreamingKit). This decreases the performance (speed) of the frequency analyzer I am using.

So the refresh of my VU-Meter view is too slow.

Maybe I'm missing something?

Thanks.

**Comment by dimitris-c** [comment]
Hey, I would really appreciate if you could provide a sample project so that I can investigate this further. 

FrameFiltering is a bit different than StreamingKit, this library uses the `installTap` to process the filters.

I can help more if I have some working example.

**Comment by iDevelopper** [comment]
Thanks,

I will provide some example project soon.
