### ISSUE TITLE
AudioStreaming not on Cocoapod

### ISSUE THREAD

**Issue by edwinzap** [dimitris-c/AudioStreaming#24]
Adding `pod 'AudioStreaming'` to the Podfile does not work because AudioStreaming does not exist on Cocoapod.
Am I missing something?

**Comment by dimitris-c** [comment]
I haven't used Cocoapod in a while, but I've missed adding the spec to their trunk repo. I've done this just now, can you confirm it works now?

**Comment by dimitris-c** [comment]
tested this and it now works
