### ISSUE TITLE
Audio not playing while silent mode is on

### ISSUE THREAD

**Issue by Flpph** [dimitris-c/AudioStreaming#26]
Hey guys!

I have an issue, where audio is only playing while the Silent Mode is off on iPhone.

Is there any way to fix this?

Thank you for your answers.

**Comment by dimitris-c** [comment]
Hey, thanks for trying out this framework 

Do you want audio to continue playing regardless the state of the Silent switch?

Have you correctly configured the category of AVAudioSession? Have a look at how it's configured in the example app.

**Comment by Flpph** [comment]
Thank you for your response, after checking the examples I found a way to do it with configuring the AVAudioSession category!
