### ISSUE TITLE
No forwarding while streaming

### ISSUE THREAD

**Issue by iUsmanN** [dimitris-c/AudioStreaming#37]
Hi,

I'm just exploring this great framework for some audio streaming and noticed that the audio does not play after I have manually scrolled the progress handle to skip half the audio. It stays paused in the example app.

Hope there's a fix for this :)

Thanks,
Usman

**Comment by dimitris-c** [comment]
I've tested the example project and it works, please note that some urls are failing and this might be the case...
I'll update the example project when I got some free time.
