### ISSUE TITLE
[Help] Gapless Playback

### ISSUE THREAD

**Issue by BLeeEZ** [dimitris-c/AudioStreaming#38]
Hi, I am currently evaluating different audio libraries to add gapless playback to my Ampache/Subsonic App: [Amperfy](https://github.com/BLeeEZ/amperfy)
I integrated AudioStream and I am able to play songs with it. 
I am still noticing a small gap between songs.
The engine is used with default configuration. The first song is played via `player.play(url: url)`. 10 seconds before the currently playing song is finished I queue the next song via `player.queue(url: url)`.
Do I need to adjust/configure something get a true gapless playback?

**Comment by dimitris-c** [comment]
Hey, thanks for raising this, is there a demo server for Amperfy that I can use to try and investigate further?

**Comment by BLeeEZ** [comment]
Thank you for your offered support. I have contacted you via your webpage so I can provide you login credentials for my demo server.

After you signed in with the Amperfy App you can navigate to playlist. There I prepared the Playlist call "Gapless". There are two songs in it "Phantom Part 1" and "Phantom Part 2". They were originally one song which I cut in two pieces. 
When the player view is open, you can tab on the icon in the upper left corner to show the currently queued songs for easier navigation.

**Comment by dimitris-c** [comment]
After some investigation I'm not sure this can be improved... Although I added the `mp3` files to the sample project and queued them and noticed a slightly less gap than your app. 

I will have it as a TODO if I can come up with anything

**Comment by dimitris-c** [comment]
And I do believe that mp3 encoding is somewhat non gapless

**Comment by BLeeEZ** [comment]
Thank you for your time and afford.

**Comment by bbsixzz** [comment]
The default Music app in iOS will play mp3 files truly gapless, at least until this happened:

[iOS 15.4 breaks 'gapless' playback in Apple Music
](https://forums.macrumors.com/threads/ios-15-4-breaks-gapless-playback-in-apple-music.2338623/)

Maybe related? 

Seems to be fixed in 15.5 betas, maybe the underlying framework is causing the gap in AudioStreaming too?

We need someone to test the beta.

**Comment by dimitris-c** [comment]
I don't think this is related to that bug `AudioStreaming` 
After researching a bit there maybe a way to remove junk from mp3 files but that would require actually knowing when and if it's needed to remove that data... more info here https://en.wikipedia.org/wiki/Gapless_playback and technical info here https://lame.sourceforge.io/tech-FAQ.txt

**Comment by bbsixzz** [comment]
Alright, other than that all I can add is that [iSub](https://github.com/einsteinx2/iSubMusicStreamer) has working true gapless playback but it's a homegrown solution. So there must be a way to do it.

**Comment by dimitris-c** [comment]
iSub uses BASS player by unseen https://www.un4seen.com under the hood - so it's quite different than AudioStreaming approach, which uses AudioFileStream from Core Audio to play audio content.

**Comment by dimitris-c** [comment]
Closing this, mp3 are not gapless by default and should have extra handling to support this.
