### ISSUE TITLE
Streaming podcast mp3 problem.

### ISSUE THREAD

**Issue by newbdez33** [dimitris-c/AudioStreaming#4]
Thanks @dimitris-c for this great project.
When you start playing for a while(example project), it will suddenly speed up extremely fast. 
Then it will loop a small piece of audio (a few seconds).
You may try to play a full podcast audio, It happens 100% chance.

I'm using iOS 14.2, Xcode 12.2

**Comment by dimitris-c** [comment]
Yeah, this was a bug which is fixed in the latest master. 
I have a few bugs to fix before cutting a new release!
