### ISSUE TITLE
AudioPlayerDelegate.audioPlayerDidStartPlaying entryId loss

### ISSUE THREAD

**Issue by xuhaoranLeo** [dimitris-c/AudioStreaming#40]
Hello, I found a issue when using the framework.

When I want to use _audioPlayerDidStartPlaying(player:with:)_ in _AudioPlayerDelegate_ to get the currently playing audio, I can't get the correct entry.

Current playing entry is nextEntry, 

<img width="526" alt="image" src="https://user-images.githubusercontent.com/14199290/178206716-9a469511-1d01-4ac8-b57f-23b906a699d0.png">

I don't know whether it was deliberately done. If so, how can I operate it better？

Look forward to your reply.

**Comment by dimitris-c** [comment]
Yes this is a bug

**Comment by dimitris-c** [comment]
fixed in latest master
