### ISSUE TITLE
iOS doesn't show audio playing on Lock Screen or Control Center

### ISSUE THREAD

**Issue by federicochiesa** [dimitris-c/AudioStreaming#43]
Both on the example app and on my own app if I play audio from a stream iOS doesn't show anything playing on the lockscreen or in Control Center. 

Is this intended behaviour?

**Comment by iDevelopper** [comment]
Yes, you can see that the example does not provide any now playing information to a MPNowPlayingInfoCenter object. You have to do this. See https://developer.apple.com/documentation/mediaplayer/mpnowplayinginfocenter

**Comment by federicochiesa** [comment]
Thank you, I must have missed that.
