### ISSUE TITLE
[Feature Request] Streaming M3U links support

### ISSUE THREAD

**Issue by federicochiesa** [dimitris-c/AudioStreaming#44]
I'm using this library for a radio streaming app and a lot of links are m3u audio streams that I can open no problem in Safari on iOS, but aren't compatible with this library. 

Any chance for this feature being added?

Here's an example m3u link that works in Safari on iOS: [link](https://streamcdnb6-4c4b867c89244861ac216426883d1ad0.msvdn.net/radiom2o/radiom2o/play1.m3u8)

**Comment by dimitris-c** [comment]
You are more than welcome to add this feature yourself and PR, I am not than happy to review this.
 
You'd need to parse the non-standard format of m3u file and then queue the links found.
