### ISSUE TITLE
Volume setting

### ISSUE THREAD

**Issue by haecksenwerk** [dimitris-c/AudioStreaming#47]
Hey!

First of all, thank you for this neat library. It drives my SwiftUI radio app. The audio streaming and ICY metadata parsing works perfectly well.

There is just one thing: Is it possible to have the player.volume setting of the AudioStreaming engine linked to the iOS volume?

**Comment by dimitris-c** [comment]
I believe you can observe the system's volume and adjust the AudioStreaming engine volume - read more here
https://developer.apple.com/documentation/avfaudio/avaudiosession/1616533-outputvolume
> You can observe changes to the value of this property by using `Key-value observing`

**Comment by haecksenwerk** [comment]
Thanks for pointing me there.
