### ISSUE TITLE
Loading audio but not autoplaying

### ISSUE THREAD

**Issue by olliekav** [dimitris-c/AudioStreaming#48]
Hey, thanks for the great library!

I have a use case where I need to load the audio file, for example to get the duration displaying but not autoplay. I was digging around the code but couldn't see any obvious way to do this apart from play then instantly pause?

**Comment by dimitris-c** [comment]
The private method `startPlayer(resetBuffers:)` does the actual start on the hardware of the audio.
Thought we would have to do quite a few changes to support that I'm afraid. 
Unfortunately I don't have the time to work on this now as I have some deadlines to finish. 

Feel free to play around if you have the time, happy to review a PR for this
