### ISSUE TITLE
MacOS Crash when connect/disconnect Airpods

### ISSUE THREAD

**Issue by longhoang2984** [dimitris-c/AudioStreaming#50]
Hi everyone! I'm building MacOS using AudioStream. I face the problem that my app crashed when I connect/disconnect my AirPods.

Xcode 14.0
AudioStreaming: latest

<img width="1460" alt="Screenshot 2023-01-11 at 04 12 32" src="https://user-images.githubusercontent.com/11419002/211663568-714e9e94-c86e-4f26-8985-ee42e7c3e1c9.png">

**Comment by dimitris-c** [comment]
Hey, I'm not sure if this is an AudioStreaming's issue but for what is worth I haven't fully supported nor tested for macOS

**Comment by longhoang2984** [comment]
@dimitris-c It has crashed when calling `player.pauseEngine` after AirPods disconnected

<img width="1452" alt="Screenshot 2023-01-11 at 20 48 04" src="https://user-images.githubusercontent.com/11419002/211822596-c32bb12d-c20e-4196-98d1-3d5545f6ad00.png">
