### ISSUE TITLE
audioPlayerDidFinishPlaying stopReason is none not eof

### ISSUE THREAD

**Issue by peterpaulis** [dimitris-c/AudioStreaming#53]
After the playback of the remote file ends, in

```
    func audioPlayerDidFinishPlaying(player: AudioStreaming.AudioPlayer,
                                     entryId: AudioStreaming.AudioEntryId,
                                     stopReason: AudioStreaming.AudioPlayerStopReason,
                                     progress: Double,
                                     duration: Double)
```

i get 

`stopReason == .none`

not `.eof`

i drilled down why this happens and its because the atomic writing block for stopReason is executed after the delegate callback, despite the atomic operation is requested earlier

iOS16

**Comment by dimitris-c** [comment]
@peterpaulis know this is a long time but this should now be fixed
