### ISSUE TITLE
macOS compatibility

### ISSUE THREAD

**Issue by halpz** [dimitris-c/AudioStreaming#57]
would it take a lot of work to make this compatible with macOS?

**Comment by dimitris-c** [comment]
Hey, I think it shouldn't be hard to support this, you are welcome to try and add this.

**Comment by AndreasInk** [comment]
I think it's as simple as this...
https://github.com/AndreasInk/AudioStreaming/blob/main/AudioStreaming/Streaming/AudioPlayer/UnitDescriptions.swift

Might have a PR up with this later today if I have some extra time :)

**Comment by dimitris-c** [comment]
Fixed #81
