### ISSUE TITLE
Crash occurs sometimes on audioPlayerDidFinishPlaying

### ISSUE THREAD

**Issue by aungkyawmon1** [dimitris-c/AudioStreaming#62]
I have found crash on Crashlytics that says audioPlayerDidFinishPlaying(player:entryId:stopReason:progress:duration:). The issue occurs sometime. Can you help me how to fix this issue.

**Comment by dimitris-c** [comment]
Can you share the symbolicated crash log from Crashlytics?

**Comment by aungkyawmon1** [comment]
Sorry for late replay. This is the text log from crashlytics.

Crashed: com.apple.main-thread

0  MyApp                           0x73428 specializedQuesAudioPlayer.audioPlayerDidFinishPlaying(player:entryId:stopReason:progress:duration:) + 163 (QuesAudioPlayer.swift:163)
1  AudioStreaming                 0x11978 $s14AudioStreaming0A6PlayerC20processFinishPlaying33_58F85687851C4E0621A9958C10937433LL5entry4withyAA0A5EntryCSg_AJtFyAJ_SbtcfU0_yycfU_ + 208
2  AudioStreaming                 0x19940 $sIeg_IeyB_TR + 28
3  libdispatch.dylib              0x26a8 _dispatch_call_block_and_release + 32
4  libdispatch.dylib              0x4300 _dispatch_client_callout + 20
5  libdispatch.dylib              0x12998 _dispatch_main_queue_drain + 984
6  libdispatch.dylib              0x125b0 _dispatch_main_queue_callback_4CF + 44
7  CoreFoundation                 0x3720c __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 16
8  CoreFoundation                 0x33f18 __CFRunLoopRun + 1996
9  CoreFoundation                 0x33668 CFRunLoopRunSpecific + 608
10 GraphicsServices               0x35ec GSEventRunModal + 164
11 UIKitCore                      0x22c2b4 -[UIApplication _run] + 888
12 UIKitCore                      0x22b8f0 UIApplicationMain + 340
13 UIKitCore                      0x4559c8 __swift_destroy_boxed_opaque_existential_1Tm + 12220
14 MyApp                           0x7d2a0 main + 4367028896 (AppDelegate.swift:4367028896)
15 ???                            0x1d3512dcc (Missing)

**Comment by dimitris-c** [comment]
Seems the crash occurs on `QuesAudioPlayer` in line 163 which should be on `audioPlayerDidFinishPlaying` method, have a look at what might go wrong there
