### ISSUE TITLE
Playing USB device audio stream

### ISSUE THREAD

**Issue by karterilla** [dimitris-c/AudioStreaming#64]
Hello and thank you for your great job.
I was wandering if your library can be used to play a constant audio stream coming from a connected USB device, an FM Radio with 2 channels.
I' trying to "update" an old application I made more than 10 years ago, ie developed on Mac which I know it is not supported (hoping yet) by your lib, but I'm stack in the old way of playback the stream coming from the device which after sometimes get corrupted or crashes the app. Even if it is compiling OK in Xcode 15.
I did use the tools and frameworks available at that time (but mostly swift code beside just the streaming written in C++...)

Thanx

**Comment by dimitris-c** [comment]
I'm not sure of how to achieve this, but you can create a new AudioSource that can read the usb data... it might work.

**Comment by karterilla** [comment]
Thank you. I was able to port the lib to macOS, but using it does not works: always getting in logs the yellow scooter "engine already running", twice, and finally the red dot "engine stopped". This just using a minimal stupid program which try to play a single url embedded in the program. Working on this right now.
So I'm miles away to try to route a stream (which actually I do not know the kind of...). Getting and buffering the stream is OK for me, I used in my failing application based on old CoreAudio, but until I do understand why your lib is unable to play an URL or a file in macOS, no way.
Thank you a lot.

**Comment by karterilla** [comment]
If you are interested I've developed a real minimal, minimal, basic Macos app that let you play URLs 9yous for example). Just those ones embedded in the program, but making a more functional, similar to your IOS one, should be not too hard. I did use it daily for days, without any issue. It uses the default system output device. Again is a pop menu to choose from, and when started you can scan over the list for other URLs without stopping and starting back.
