### ISSUE TITLE
Paused audio plays for a short time before starts playing new audio

### ISSUE THREAD

**Issue by amralharazi** [dimitris-c/AudioStreaming#68]
First of all, thank you for this library. It really did help me starting playing audios faster than using Apple's out-of-the-box solution.

But, I've just noticed an issue, not sure if that's something on my side. When an audio is paused, then another audio is set to be played, the previous audio starts playing for a faction of a second then the new audio starts playing. 

I was in a hurry, so after some trial and error, I figured that stopping the player and changing the _play(url: URL, headers: [String: String])_ method in _AudioPlayer_ to the following did the trick , but that's not a perfect solution for sure. 
```
    public func play(url: URL, headers: [String: String]) {
        let audioEntry = entryProvider.provideAudioEntry(url: url, headers: headers)
        audioEntry.delegate = self
        
        checkRenderWaitingAndNotifyIfNeeded()
        sourceQueue.async { [weak self] in
            guard let self = self else { return }
            
            clearQueue()
            entriesQueue.enqueue(item: audioEntry, type: .upcoming)
            playerContext.setInternalState(to: .pendingNext)
            do {
                try self.startEngineIfNeeded()
            } catch {
                self.raiseUnexpected(error: .audioSystemError(.engineFailure))
            }
            self.processSource()
        }
    }
```

Thank you again and I'd appreciate your feedback to this issue.

**Comment by dimitris-c** [comment]
Thanks for reporting this. will have a look

**Comment by dimitris-c** [comment]
This is fixed on the main branch, a new release will be up soon with this fix.
