### ISSUE TITLE
Mixing Multiple Audios Simultaneously 

### ISSUE THREAD

**Issue by GitCors** [dimitris-c/AudioStreaming#70]
Hello,

I want my app to be able to play multiple audio URLs simultaneously. Could you please provide guidance or hints on how I can achieve this? Any assistance would be greatly appreciated.

Thank you!

**Comment by dimitris-c** [comment]
This library doesn't support multiple audio simultaneously. You could create multiple instances of AudioPlayer but I would advise against it.
