### ISSUE TITLE
App Crashing when playing a URL

### ISSUE THREAD

**Issue by adilfarooq-iways** [dimitris-c/AudioStreaming#74]
The application crashed after some time, when tried to play with a url.

IOS: 16
SWIFT UI

<img width="1674" alt="Screenshot 2024-04-09 at 4 22 52 PM" src="https://github.com/dimitris-c/AudioStreaming/assets/102814724/d80fac67-0aea-4c3f-964a-f451b6a1369f">

**Comment by dimitris-c** [comment]
I haven't seen this crash, will have a look at it, but I would be remiss if I didn't mention the fact that creating the AudioPlayer inside a Button action is incorrect, this will cause the AudioPlayer to be recreated on each tap of the button which might have undesired effects.

**Comment by dimitris-c** [comment]
can't reproduce
