### ISSUE TITLE
Player's state does not update after marking buffering

### ISSUE THREAD

**Issue by ishaanbedi** [dimitris-c/AudioStreaming#83]
Hey! Thanks for the amazing library.

I'm observing the changes in the audio player using:
```swift
.onChange(of: player.state, { oldValue, newValue in
            print(oldValue, newValue)
})
```

I'd like to bind back the new state to a variable, specifically when the audio starts playing, logically the buffering status should go away. 

While everything works as expected, the buffering state should update to something like "playing", which currently does not get updated. 

Here's the example log from the console:

<img width="594" alt="Screenshot 2024-05-24 at 4 41 32 PM" src="https://github.com/dimitris-c/AudioStreaming/assets/39641326/af01f1fa-e237-4b65-8ab1-73278243f3d2">

Please correct me if I'm doing something wrong here. Again, thanks!

**Comment by dimitris-c** [comment]
Hey, I would suggest that instead of listening changes on the `player.state` to utilise the delegate methods and update a local state on the Observable model.

**Comment by ishaanbedi** [comment]
> Hey, I would suggest that instead of listening changes on the player.state to utilise the delegate methods and update a local state on the Observable model.

Makes sense, will try that!

Thank you!
