### ISSUE TITLE
App based on AudioStreaming crashed when compiled for release 

### ISSUE THREAD

**Issue by op183** [dimitris-c/AudioStreaming#84]
I tested simple cli utility which occasionally crash if compiled in release mode. It never crashed if compiled in debug mode :-). Please check https://developer.apple.com/documentation/os/osallocatedunfairlock 

What is apple suggested?

If you’ve existing Swift code that uses [os_unfair_lock](https://developer.apple.com/documentation/os/os_unfair_lock), change it to use [OSAllocatedUnfairLock](https://developer.apple.com/documentation/os/osallocatedunfairlock) to ensure correct locking behavior.

**Comment by dimitris-c** [comment]
Hey, `OSAllocatedUnfairLock` is only available on iOS 16+, might take some time to add it for iOS 16+ only
