### ISSUE TITLE
FrameFiltering

### ISSUE THREAD

**Issue by op183** [dimitris-c/AudioStreaming#85]
What do I naively do while hoping to support silent recording?

I tried to memset Chanel data to 0 after writing the buffer to audio file, without any success. :-) :-) :-)

The reason is obvious, FrameFiltering uses a tap on the main mixer output, which is great for recording or observing audio data, unfortunately, there is also no chance to manipulate audio volume without affecting the recording result.

Do you have any idea how to solve this?

PS: it is mentioned in the documentation, but you know, whoever read the documentation? Maybe FrameFiltering sounds like the best place to filter the output audio for me only …

**Comment by dimitris-c** [comment]
FrameFiltering is indeed only for observation of the audio that has been passed to the AVAudioEngine, you can't manipulate the audio from FrameFiltering.

You could introduce a new `AVAudioMixerNode` (_preMixer_) pass this instance to the `mixerNodeProvider` of `FrameFilterProcessor` and then on `attachAndConnectDefaultNodes` method you need to attach the mixer to the engine and do a connection of
rateNode -> preMixer ->  audioEngine.mainMixerNode

This was you could set the player.volume to 0 but still record the audio.

**Comment by op183** [comment]
> FrameFiltering is indeed only for observation of the audio that has been passed to the AVAudioEngine, you can't manipulate the audio from FrameFiltering.
> 
> You could introduce a new `AVAudioMixerNode` (_preMixer_) pass this instance to the `mixerNodeProvider` of `FrameFilterProcessor` and then on `attachAndConnectDefaultNodes` method you need to attach the mixer to the engine and do a connection of rateNode -> preMixer -> audioEngine.mainMixerNode
> 
> This was you could set the player.volume to 0 but still record the audio.

This is exactly I already did as my first step, without modifications in the framework. Thank you for your response!
